transport:
  type: "obd2"
  connection_type: "ble"
  ble_address: "9F94D6BB-D772-0557-976D-6DA82685018D"
  ble_service_uuid: "0000ffe0-0000-1000-8000-00805f9b34fb"
  ble_write_char_uuid: "0000ffe1-0000-1000-8000-00805f9b34fb"
  ble_notify_char_uuid: "0000ffe1-0000-1000-8000-00805f9b34fb"
  timeout_sec: 5.0
  update_interval_sec: 1.0
  pid_path: "pids/leaf_aze0.yaml"
  reconnect_delay_sec: 5.0

logging:
  enabled: true
  path: "./logs"
  level: "DEBUG"

vehicle:
  year: 2013
  generation: "AZE0"
  model: "SV"
  pack_kwh: 24.0
  cell_count: 96
